export default function checkLocalStorage() {
  //checks if there is any data stored in the browser's local storage under the key "invoices"
  window.localStorage.getItem("invoices") === null &&
    window.localStorage.setItem(
      "invoices",
      JSON.stringify([
        {
          id: "RT3080",
          street: "19 Union Terrace",
          city: "London",
          post: "E1 3EZ",
          country: "United Kingdom",
          clientName: "Jensen Huang",
          clientEmail: "jensenh@mail.com",
          clientStreet: "106 Kendell Street",
          clientCity: "Sharrington",
          clientPost: "NR24 5WQ",
          clientCountry: "United Kingdom",
          date: "2021-08-18",
          payment: "1",
          description: "Re-branding",
          items: [
            {
              id: "09fecfe7-a98c-472e-85e6-54bef30e7ebc",
              itemName: "Brand Guidelines",
              price: "1800.90",
              qty: "1",
              total: 1800.9,
            },
          ],
          granTotal: 1800.9,
          status: "Paid",
        },
        {
          id: "XM9141",
          street: "19 Union Terrace",
          city: "London",
          post: "E1 3EZ",
          country: "United Kingdom",
          clientName: "Alex Grim",
          clientEmail: "alexgrim@mail.com",
          clientStreet: "84 Church Way",
          clientCity: "Bradford",
          clientPost: "BD1 9PB",
          clientCountry: "United Kingdom",
          date: "2021-08-21",
          payment: "30",
          description: "Graphic Design",
          items: [
            {
              id: "2b65b40c-d107-408b-9c5f-73aa81f75c29",
              itemName: "Banner Design",
              price: "156.00",
              qty: "1",
              total: 156.0,
            },
            {
              id: "2b65b40c-d107-408b-9c5f-73aa81f75c60",
              itemName: "Email Design",
              price: "200.00",
              qty: "2",
              total: 400.0,
            },
          ],
          granTotal: "556.00",
          status: "Pending",
        },
        {
          id: "RG0314",
          street: "19 Union Terrace",
          city: "London",
          post: "E1 3EZ",
          country: "United Kingdom",
          clientName: "John Morrison",
          clientEmail: "jm@myco.com",
          clientStreet: "79 Dover Road",
          clientCity: "Westhall",
          clientPost: "IP19 3PF",
          clientCountry: "United Kingdom",
          date: "2021-09-24",
          payment: "7",
          description: "Website Redesign",
          items: [
            {
              id: "46ddc8d3-53ad-4e0e-bf2d-a49cf4f8f6da",
              itemName: "Website Redesign",
              price: "14002.33",
              qty: "1",
              total: 14002.33,
            },
          ],
          granTotal: 14002.33,
          status: "Paid",
        },
        {
          id: "RT2080",
          street: "19 Union Terrace",
          city: "London",
          post: "E1 3EZ",
          country: "United Kingdom",
          clientName: "Alysa Werner",
          clientEmail: "alysa@email.co.uk",
          clientStreet: "63 Warwick Road",
          clientCity: "Carlisle",
          clientPost: "CA20 2TG",
          clientCountry: "United Kingdom",
          date: "2021-10-11",
          payment: "1",
          description: "Logo Concept",
          items: [
            {
              id: "d0dc2b63-5c73-418b-be8f-737ca12ffa31",
              itemName: "Logo Sketches",
              price: "102.04",
              qty: "1",
              total: 102.04,
            },
          ],
          granTotal: 102.04,
          status: "Pending",
        },
        {
          id: "AA1449",
          street: "19 Union Terrace",
          city: "London",
          post: "E1 3EZ",
          country: "United Kingdom",
          clientName: "Mellisa Clarke",
          clientEmail: "mellisa.clarke@example.com",
          clientStreet: "46 Abbey Row",
          clientCity: "Cambridge",
          clientPost: "CB5 6EG",
          clientCountry: "United Kingdom",
          date: "2021-10-7",
          payment: "7",
          description: "Re-branding",
          items: [
            {
              id: "7fa42a71-78b9-4920-a53c-9de94dc41554",
              itemName: "New Logo",
              price: "20500",
              qty: "1",
              total: 1532.33,
            },
            {
              id: "7fa42a71-78b9-4920-a53c-9de94dc41560",
              itemName: "Brand Guidelines",
              price: "2500.00",
              qty: "1",
              total: 2500.0,
            },
          ],
          granTotal: 4032.33,
          status: "Pending",
        },
        {
          id: "TY9141",
          street: "19 Union Terrace",
          city: "London",
          post: "E1 3EZ",
          country: "United Kingdom",
          clientName: "Thomas Wayne",
          clientEmail: "thomas@dc.com",
          clientStreet: "3964  Queens Lane",
          clientCity: "Gotham",
          clientPost: "60457",
          clientCountry: "United States of America",
          date: "2021-10-01",
          payment: "30",
          description: "Landing Page Design",
          items: [
            {
              id: "7fa42a71-78b9-4920-a53c-9de94dc41561",
              itemName: "Web Design",
              price: "6155.91",
              qty: "1",
              total: 6155.91,
            },
          ],
          granTotal: 6155.91,
          status: "Pending",
        },
        {
          id: "FV2353",
          street: "19 Union Terrace",
          city: "London",
          post: "E1 3EZ",
          country: "United Kingdom",
          clientName: "Anita Wainwright",
          clientEmail: "",
          clientStreet: "",
          clientCity: "",
          clientPost: "",
          clientCountry: "",
          date: "2021-11-05",
          payment: "7",
          description: "Logo Re-design",
          items: [
            {
              id: "7fa42a71-78b9-4920-a53c-9de94dc41561",
              itemName: "Logo Re-design",
              price: "3102.04",
              qty: "1",
              total: 3102.04,
            },
          ],
          granTotal: 3102.04,
          status: "Draft",
        },
      ])
    );
}
/**
 * The function checks if there is any data stored in the browser's local storage under the key "invoices". If there isn't any data, the function will store an array of five objects with sample invoice data.
 */
